### ISSUE TITLE
Support globbing

### ISSUE THREAD

**Issue by phated** [FotoVerite/pg-annotate#2]
I would love to run this against a directory by using `sql/*.sql` as the `filename` argument.

**Comment by FotoVerite** [comment]
Globbing  works fine. What's the easiest way to sync up when all the files are done. event emitter? we need to basically watch and tick off an index till all async are done.

**Comment by phated** [comment]
Globbing on a *nix OS might work fine, but that stuff doesn't fly on a
Windows machine. What do you need to sync at the end for?

**Comment by FotoVerite** [comment]
Wait how should I do it on windows? Fs reader won't work? 

—

**Comment by phated** [comment]
I was thinking the node-glob module by isaacs

**Comment by FotoVerite** [comment]
You need to sync to exit process and output each file that is being updated 

—
